### ISSUE TITLE
Remove admin dashboard cards view from normal users

### ISSUE THREAD

**Issue by pcnoic** [pcnoic/emmaview#30]
### Overview

Normal users should not be able to view the dashboard statistics cards when logged into the dashboard. 

![Screenshot from 2021-07-08 20-28-36](https://user-images.githubusercontent.com/12615106/124965716-1c6c3080-e02b-11eb-877e-6f0d7037f86d.png)

### Tasks 
- remove the cards when the user is not an administrator. 

### Acceptance Criteria

When a regular user logins to the dashboard he can't see the admin statistics cards.

**Comment by marinoszago** [comment]
Done to be pushed
