### ISSUE TITLE
Remove admin menu items from regular users 

### ISSUE THREAD

**Issue by pcnoic** [pcnoic/emmaview#31]
### Overview

When logged in to the administrator panel a regular user should not have the following options in the left drawer menu.

![Screenshot from 2021-07-08 20-30-42](https://user-images.githubusercontent.com/12615106/124966107-8edd1080-e02b-11eb-9c61-fc908af2569e.png)

### Tasks

- hide admin menu items for regular users in the dashboard left drawer

### Acceptance Criteria

A regular user cannot view the admin menu items in the dashboard left drawer.

**Comment by marinoszago** [comment]
Done to be pushed
