### ISSUE TITLE
Change font color in login window 

### ISSUE THREAD

**Issue by pcnoic** [pcnoic/emmaview#32]
### Overview

The color of the font in the login window is currently white. The background is also white. Thus, the text is not visible to the user.

![image](https://user-images.githubusercontent.com/12615106/124966378-eaa79980-e02b-11eb-97ff-e595ce871255.png)

### Tasks 
- change the font color to gray/black

### Acceptance Criteria

When a regular user visit the login window, all the text that is displayed is visible

**Comment by marinoszago** [comment]
Done to be pushed
