### ISSUE TITLE
Hide "Users location" menu item from main left drawer for regular users

### ISSUE THREAD

**Issue by pcnoic** [pcnoic/emmaview#33]
### Overview

Regular users should not have access to the shared locations of other users. Even though an API restriction is in place and the actual locations cannot be fetched without an administrator account, the menu item should also be hidden for regular users to improve UX.

![image](https://user-images.githubusercontent.com/12615106/124966929-82a58300-e02c-11eb-99d1-87ae706a894a.png)

### Tasks 
- remove the "Users Location" menu item from the main left drawer for regular users

### Acceptance Criteria

Regular users cannot view the menu item "Users Location" in the main left drawer

**Comment by marinoszago** [comment]
Done.. to be pushed
