### ISSUE TITLE
Overlapping UI elements in landing page

### ISSUE THREAD

**Issue by pcnoic** [pcnoic/emmaview#37]
### Overview

There are overlapping UI elements in the `landing` page. Specifically, the slider object and the weather object are overlapping, as depicted in the following picture.

![Screenshot from 2021-07-10 13-18-00](https://user-images.githubusercontent.com/12615106/125159665-71ba5600-e181-11eb-84de-9b55704780c2.png)

### Tasks
- make the position of these two UI elements `relative` to each other, so they avoid collision. 

### Acceptance Criteria

The UI elements in the `landing` page no longer overlap.

**Comment by marinoszago** [comment]
Done to be pushed
